djaken/urls.py
from django.conf.urls import url

from . import views

app_name = 'djaken'

urlpatterns = [
    url(r'^$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^all_notes/$', views.all_notes, name='all_notes'),
    url(r'^all_notes/toggle_relevant/$', views.all_notes, kwargs={'toggle_relevant':True}, name='all_notes_toggle_relevant'),
    url(r'^all_notes/sort_by_relevant/$', views.all_notes, kwargs={'sort_by':'relevant'}, name='all_notes_sort_by_relevant'),
    url(r'^all_notes/sort_by_modified/$', views.all_notes, kwargs={'sort_by':'modified'}, name='all_notes_sort_by_modified'),
    url(r'^all_notes/sort_by_created/$', views.all_notes, kwargs={'sort_by':'created'}, name='all_notes_sort_by_created'),
    url(r'^new_note/$', views.new_note, name='new_note'),
    url(r'^view_note/(?P<pk>[0-9]+)', views.view_note, name='view_note'),
    url(r'^view_note/toggle_relevant/(?P<pk>[0-9]+)/$', views.view_note, kwargs={'toggle_relevant':True}, name='view_note_toggle_relevant'),
    url(r'^edit_note/(?P<pk>[0-9]+)/$', views.edit_note, name='edit_note'),
    url(r'^unlock_note/(?P<pk>[0-9]+)/$', views.unlock_note, name='unlock_note'),
    url(r'^save_note/(?P<pk>[0-9]+)/$', views.save_note, name='save_note'),
]

djaken/templates/djaken/all_notes.html
{% extends 'djaken/base.html' %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "djaken/css/all_notes.css" %}" />{% endblock %}

{% block content %}
    <div class="search_and_new">
        <table class="outer">
            <tr>
                <td>
                    <table class="inner">
                        <tr>
                            <td> 
                                <a class="search_button" id="search_button" title="{% trans 'Search within note' %}" href="{% url 'djaken:all_notes' %}?sort_order={{sort_order}}&only_relevant={{only_relevant}}&search={{ search_text }}"></a>
                            </td>
                            <td>
                                <form>
                                    <input type="text" id="search_text" name="search" value="{{ search_text }}" maxlength="255" onchange="getSearchText()" onkeypress="return searchKeyPress(event)" />
                                    <input type="hidden" id="sort_order" value="{{sort_order}}" />
                                    <input type="hidden" id="only_relevant" value="{{only_relevant}}" />
                                </form>
                            </td>
                            <td>
                                <a class="erase_button" id="erase_button" title="{% trans 'Clear search criteria' %}"  href="{% url 'djaken:all_notes' %}?sort_order={{sort_order}}&only_relevant={{only_relevant}}&search="></a>
                            </td>
                        </tr>
                    </table>
                </td>
                <td class="new_note_button">
                    <a class="new_note_button" title="{% trans 'New note' %}" href="{% url 'djaken:new_note' %}"></a>
                </td>
            </tr>
        </table>
    </div>
    <div class="filters">
        <table class="outer">
            <tr>
                <td>
                    <table class="inner">
                       <tr>
                           <td class="filter_label">
                               <p> {% trans 'Sort by:' %} </p>
                           </td>
                           {% for item in sort_order %}
                               <td>
                                   {% if item == "-relevant" or item == "relevant" %}
                                       <p>{% trans 'Relevant' %}</p>
                                   {% endif %}
                                   {% if item == "-modified" or item == "modified" %}
                                       <p>{% trans 'Modified' %}</p>
                                   {% endif %}
                                   {% if item == "-created" or item == "created" %}
                                       <p>{% trans 'Created' %}</p>
                                   {% endif %}
                               </td>
                               <td class="filter_buttons">
                                   {% if item == "-relevant" %}
                                       <a title="{% trans 'Sort by ascending relevancy' %}" href="{% url 'djaken:all_notes_sort_by_relevant' %}?sort_order={{sort_order}}&only_relevant={{only_relevant}}&search={{search_text}}"> <div class="arrow_down"> </div> </a>
                                   {% endif %}
                                   {% if item == "relevant" %}
                                       <a title="{% trans 'Sort by descending relevancy' %}" href="{% url 'djaken:all_notes_sort_by_relevant' %}?sort_order={{sort_order}}&only_relevant={{only_relevant}}&search={{search_text}}"> <div class="arrow_up"> </div> </a>
                                   {% endif %}
                                   {% if item == "-modified" %}
                                       <a title="{% trans 'Sort by ascending modified time' %}" href="{% url 'djaken:all_notes_sort_by_modified' %}?sort_order={{sort_order}}&only_relevant={{only_relevant}}&search={{search_text}}"> <div class="arrow_down"> </div> </a>
                                   {% endif %}
                                   {% if item == "modified" %}
                                       <a title="{% trans 'Sort by descending modified time' %}" href="{% url 'djaken:all_notes_sort_by_modified' %}?sort_order={{sort_order}}&only_relevant={{only_relevant}}&search={{search_text}}"> <div class="arrow_up"> </div> </a>
                                   {% endif %}
                                   {% if item == "-created" %}
                                       <a title="{% trans 'Sort by ascending created time' %}" href="{% url 'djaken:all_notes_sort_by_created' %}?sort_order={{sort_order}}&only_relevant={{only_relevant}}&search={{search_text}}"> <div class="arrow_down"> </div> </a>
                                   {% endif %}
                                   {% if item == "created" %}
                                       <a title="{% trans 'Sort by descending created time' %}" href="{% url 'djaken:all_notes_sort_by_created' %}?sort_order={{sort_order}}&only_relevant={{only_relevant}}&search={{search_text}}"> <div class="arrow_up"> </div> </a>
                                   {% endif %}
                               </td>
                           {% endfor %}
                           <td class="filter_label">
                               <p>{% trans 'Relevant?:' %}</p>
                           </td>
                           <td class="filter_buttons">
                               {% if only_relevant == True %}
                                   <a title="{% trans 'Show irrelevant notes too' %}" href="{% url 'djaken:all_notes_toggle_relevant' %}?sort_order={{sort_order}}&only_relevant={{only_relevant}}&search={{search_text}}" class="toggle-control toggle-on"></a>
                               {% else %}
                                   <a title="{% trans 'Show only relevant notes' %}" href="{% url 'djaken:all_notes_toggle_relevant' %}?sort_order={{sort_order}}&only_relevant={{only_relevant}}&search={{search_text}}" class="toggle-control"></a>
                               {% endif %}
                           </td>
                       </tr>
                    </table>
                </td>
            </tr>
        </table>
    </div>
    {% for note in notes %}
    <div class="each_note">
        <h2>
            <a title="{% trans 'View this note' %}" href="{% url 'djaken:view_note' note.pk %}">
                {{note.title}}
            </a>
        </h2>
        <table class="outer">
            <tr>
                <td>
                    <table class="inner">
                        <tr>
                            <td>
                                {% if note.is_encrypted %}
                                    <p class="encryption_icon"></p>
                                {% endif %}
                            </td>
                            <td>
                                {% if note.relevant %}
                                    <p class="note_relevant">
                                        {% trans 'Relevant' %}
                                    </p>
                                {% endif %}
                                {% if not note.relevant %}
                                    <p class="note_not_relevant">
                                        {% trans 'Not Relevant' %}
                                    </p>
                                {% endif %}
                            </td>
                            <td>
                                <p>
                                    {% trans 'Modified on' %}
                                    <time datetime="{{note.modified|date:"c"}}">
                                        {{note.modified|date}}
                                    </time> 
                                </p>
                            </td>
                            <td>
                                <p>
                                    {% trans 'Created on' %}
                                    <time datetime="{{note.created|date:"c"}}">
                                        {{note.created|date}}
                                    </time> 
                                </p>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
        </p>
    </div>
    {% endfor %}
    <script ="text/javascript">
        function getSearchText() {
            var searchText = document.getElementById("search_text").value;
            var sortOrder = document.getElementById("sort_order").value;
            var onlyRelevant = document.getElementById("only_relevant").value;
            document.getElementById("search_button").setAttribute("href", "{% url 'djaken:all_notes' %}?sort_order=" + sortOrder + "&only_relevant=" + onlyRelevant + "&search=" + searchText);
        }
        function searchKeyPress(e)
        {
            // look for window.event in case event isn't passed in
            e = e || window.event;
            if (e.keyCode == 13)
            {
                getSearchText();
                document.getElementById("search_button").click();
                return false;
            }
            return true;
        }
    </script>
{% endblock %}

djaken/templates/djaken/base.html
{% load i18n static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<title>{% block title %}{{ page_title }} | {{ site_title|default:_('Djaken') }}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "djaken/css/base.css" %}{% endblock %}" />
{% block extrastyle %}{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>

{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}"
  data-admin-utc-offset="{% now "Z" %}">

<!-- Container -->
<div id="container">

    {% if not is_popup %}

    <!-- Header -->
    <div id="header">
        <div id="branding">
        {% block branding %}<h1 id="site-header"><a href="{% url 'djaken:all_notes' %}">{{ site_header|default:_('Djaken Notes') }}</a></h1>{% endblock %}
        </div>
        {% block usertools %}
        {% if user_is_logged_in %}
        <div id="user-tools">
            {% block welcome-msg %}
                {% trans 'Welcome,' %}
                <strong>{% firstof user.get_short_name user.get_username %}</strong>.
            {% endblock %}
            {% block userlinks %}
                <a href="{% url 'djaken:logout' %}">{% trans 'Log out' %}</a>
            {% endblock %}
        </div>
        {% endif %}
        {% endblock %}
    </div>
    <!-- END Header -->

    {% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="{% url 'djaken:all_notes' %}">{{ site_title|default:_('Djaken') }}</a>
    {% if page_title %} &rsaquo; {{ page_title }}{% endif %}
    </div>
    {% endblock %}
    {% endif %}

    {% block messages %}
        {% if messages %}
        <ul class="messagelist">{% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
        {% endfor %}</ul>
        {% endif %}
    {% endblock messages %}

    <!-- Content -->
    <div class="content_title">
        {% block content_title %}{% if content_title %}<h1>{{ content_title }}</h1>{% endif %}{% endblock %}
    </div>
    <div id="content">
        {% block content %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>
    <!-- END Content -->

    {% block footer %}<div id="footer"></div>{% endblock %}
</div>
<!-- END Container -->

</body>
</html>

djaken/templates/djaken/edit_note.html
{% extends 'djaken/base.html' %}
{% load i18n static %}

{% block extrastyle %}
{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "djaken/css/edit_note.css" %}" />
<meta charset=utf-8 />
{% endblock %}

{% block title %}{{note.title}} | {{ site_title|default:_('Djaken') }}{% endblock %}

{% block content %}
    <div class="controls">
        <table class="outer">
            <tr>
                <td>
                    <table class="inner">
                        <tr>
                            <td class="control_button">
                                <a class="save_and_view_button" title="{% trans 'Save and view note' %}" onclick="return viewAfterSave()"></a>
                            </td>
                            <td class="control_button">
                                <a class="save_button" title="{% trans 'Save note' %}" onclick="return continueAfterSave()"></a>
                            </td>
                            <td class="control_button">
                                <a class="view_button" title="{% trans 'View note' %}" href="{% url 'djaken:view_note' note.pk %}"></a>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </div>
    <div class="note_content">
        <form action="{% url 'djaken:save_note' note.pk %}" method="post">
            {% csrf_token %}
            <br>
            <label for="note_title">{% trans 'Title' %}</label>
            <br>
            <input type="text" name="note_title" id="note_title" value="{{ note.title }}" maxlength="255" />
            <br>
            <br>
            <label for="note_content">{% trans 'Content' %}</label>
            <br>
            <textarea name="note_content" id="note_content">{{ note_content }}</textarea>
            <br>
            <br>
            <hr>
            <br>
            <label for="image_attach_selector">{% trans 'Attach Image' %}</label>
            <br>
            <table class="image_attach"><tr>
            <td><div class="image_attach_selector">
            <input type="file" name="image_attach_selector" id="image_attach_selector" title="{% trans 'Select image' %}" accept="image/gif, image/jpeg, image/png" onchange="readURL(this)"/>
            </div></td>
            <td><a class="save_button" id="image_attach_save" title="{% trans 'Save selected image' %}" style="display: none" onclick="return imageAttachSave()"></a></td>
            <td><a class="erase_button" id="image_attach_clear" title="{% trans 'Clear selected image' %}" style="display: none" onclick="return clearImageAttach()"></a></td>
            </tr></table>
            <br>
            <label for="image_preview">{% trans 'Image Preview' %}</label>
            <br>
            <img id="image_preview" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFAAAABQCAIAAAABc2X6AAAAA3NCSVQICAjb4U/gAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAqElEQVR4nO3csQ3AIAwAQRMxGINQMhqDMFpmcKrw/quDpRcVspS21opKekTMOVNnzjmp78cYP5m/935SowEMpjOYzmA6g+kMpjOYzmC6Hje/bz/ML3fDBtMZTGcwncF0BtMZTGcwXY/L37ep+e6HCzCYzmA6g+kMpjOYzmC6csHuh+kMpjOYzmA6g+kMpjOYzmA698N0BtMZTGcwncF0BtMZTNeq/V7qBQTYLdl+Vm1PAAAAAElFTkSuQmCC" alt="{% trans 'Attached Image' %}" />
            <br>
            <hr>
            <br>
            <label for="is_encrypted"> {% trans 'Encrypted' %} </label>
            <input type="checkbox" name="is_encrypted" id="is_encrypted" value="is_encrypted" {% if note.is_encrypted %} checked {% endif %} onclick="is_encryptedClicked()" />
            <input type="password" name="encrypt_pass" id="encrypt_pass" value="" {% if note.is_encrypted %} required {% endif %} />
            <br>
            <br>
            <hr>
            <input type="hidden" name="preview_image_data" id="preview_image_data" value="" />
            <input type="hidden" name="continue_after_save" id="continue_after_save" value="False" />
            <input type="hidden" name="attach_during_save" id="attach_during_save" value="False" />
            <input type="submit" id="save_form" value="{% trans 'Save & View' %}" />
            <br>
        </form>
    </div>
    <div class="controls">
        <table class="outer">
            <tr>
                <td>
                    <table class="inner">
                        <tr>
                            <td class="control_button">
                                <a class="save_and_view_button" title="{% trans 'Save and view note' %}" onclick="return viewAfterSave()"></a>
                            </td>
                            <td class="control_button">
                                <a class="save_button" title="{% trans 'Save note' %}" onclick="return continueAfterSave()"></a>
                            </td>
                            <td class="control_button">
                                <a class="view_button" title="{% trans 'View note' %}" href="{% url 'djaken:view_note' note.pk %}"></a>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </div>
    <br>
    <br>
    <div class="footer">
        {% if note.is_encrypted %}
            <p class="encryption_icon"></p>
        {% endif %}
        {% if note.relevant %}
            <p class="note_relevant">
                {% trans 'Relevant' %}
            </p>
        {% endif %}
        {% if not note.relevant %}
            <p class="note_not_relevant">
                {% trans 'Not Relevant' %}
            </p>
        {% endif %}
        <p>
            {% trans 'Modified on' %}
            <time datetime="{{note.modified|date:"c"}}">
                {{note.modified|date}}
            </time>
        </p>
        <p>
            {% trans 'Created on' %}
            <time datetime="{{note.created|date:"c"}}">
                {{note.created|date}}
            </time>
        </p>
    </div>
    <script = "text/javascript">
        window.onload = function() {
            history.replaceState("", "", "/edit_note/{{note.id}}");
        }
        function toggleImageAttachSaveButton() {
            var btn = document.getElementById("image_attach_save");
            if (btn.style.display === "none")
            {
                btn.style.display = "block";
            }
            else
            {
                btn.style.display = "none";
            }
        }
        function toggleImageAttachClearButton() {
            var btn = document.getElementById("image_attach_clear");
            var imageAttachSelector = document.getElementById("image_attach_selector");
            var imageAttachSelectorDiv = document.getElementsByClassName("image_attach_selector");
            if (btn.style.display === "none")
            {
                btn.style.display = "block";
                imageAttachSelector.setAttribute('disabled', 'disabled');
                imageAttachSelectorDiv[0].style.opacity = "0.3";
            }
            else
            {
                btn.style.display = "none";
                imageAttachSelector.removeAttribute('disabled');
                imageAttachSelectorDiv[0].style.opacity = "1.0";
                imageAttachSelector.value = "";
            }
        }
        function clearImageAttach() {
            document.getElementById("image_preview").src = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFAAAABQCAIAAAABc2X6AAAAA3NCSVQICAjb4U/gAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAqElEQVR4nO3csQ3AIAwAQRMxGINQMhqDMFpmcKrw/quDpRcVspS21opKekTMOVNnzjmp78cYP5m/935SowEMpjOYzmA6g+kMpjOYzmC6Hje/bz/ML3fDBtMZTGcwncF0BtMZTGcwXY/L37ep+e6HCzCYzmA6g+kMpjOYzmC6csHuh+kMpjOYzmA6g+kMpjOYzmA698N0BtMZTGcwncF0BtMZTNeq/V7qBQTYLdl+Vm1PAAAAAElFTkSuQmCC";
            document.getElementById("preview_image_data").value = "";
            toggleImageAttachSaveButton();
            toggleImageAttachClearButton();
        }
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    var image_data = e.target.result
                    document.getElementById("image_preview").src = image_data
                    document.getElementById("preview_image_data").value = image_data
                };
                reader.readAsDataURL(input.files[0]);
                toggleImageAttachSaveButton();
                toggleImageAttachClearButton();
            }
        }
        function viewAfterSave() {
            document.getElementById("continue_after_save").value = "False";
            document.getElementById("save_form").click();
        }
        function continueAfterSave() {
            document.getElementById("continue_after_save").value = "True";
            document.getElementById("save_form").click();
        }
        function imageAttachSave() {
            document.getElementById("continue_after_save").value = "True";
            document.getElementById("attach_during_save").value = "True";
            document.getElementById("save_form").click();
        }
        function is_encryptedClicked() {
            if (document.getElementById('is_encrypted').checked)
            {
                document.getElementById('encrypt_pass').required = true;
            }
            else
            {
                document.getElementById('encrypt_pass').required = false;
            }
        }
    </script>
{% endblock %}

djaken/templates/djaken/login.html
{% extends "djaken/base.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "djaken/css/login.css" %}" />
{{ form.media }}
{% endblock %}

{% block bodyclass %}{{ block.super }} login{% endblock %}

{% block usertools %}{% endblock %}

{% block content_title %}{% endblock %}
 
{% block breadcrumbs %}{% endblock %}

{% block content %}
{% if form.errors and not form.non_field_errors %}
<p class="errornote">
{% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
</p>
{% endif %}

{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<p class="errornote">
    {{ login_error_text }}
</p>
{% endfor %}
{% endif %}

<div id="content-login">
<form action="{{ app_path }}" method="post" id="login-form">{% csrf_token %}
  <div class="form-row">
    {{ form.username.errors }}
    {{ form.username.label_tag }} {{ form.username }}
  </div>
  <div class="form-row">
    {{ form.password.errors }}
    {{ form.password.label_tag }} {{ form.password }}
    <input type="hidden" name="next" value="{{ next }}" />
  </div>
  <div class="submit-row">
    <label>&nbsp;</label><input type="submit" value="{% trans 'Log in' %}" />
  </div>
</form>

<script type="text/javascript">
document.getElementById('id_username').focus()
</script>
</div>
{% endblock %}

djaken/templates/djaken/unlock_note.html
{% extends 'djaken/base.html' %}
{% load i18n static %}

{% block extrastyle %}
{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "djaken/css/unlock_note.css" %}" />
<meta charset=utf-8 />
{% endblock %}

{% block title %}{{note.title}} | {{ site_title|default:_('Djaken') }}{% endblock %}

{% block content %}
    <div class="note_content">
        <form id="unlock_note_form" action="{% url 'djaken:unlock_note' note.pk %}" method="post">
            {% csrf_token %}
            <br>
            <label for="encrypt_pass">{% trans 'Encryption Password' %}</label>
            <input type="password" name="encrypt_pass" id="encrypt_pass" value="" autofocus required />
            <br>
            <br>
            <hr>
            <br>
            <input type="hidden" name="next_url" id="next_url" value="{{ next_url }}" />
            <input type="submit" id="unlock_note" value="{% trans 'Unlock Note' %}" />
            <a class="unlock_note" title="{% trans 'Unlock Note' %}" onclick="return submitPassword()"></a>
        </form>
    </div>
    <script = "text/javascript">
        function submitPassword() {
            document.getElementById("unlock_note").click();
        }
    </script>
{% endblock %}

djaken/templates/djaken/view_note.html
{% extends 'djaken/base.html' %}
{% load i18n static %}

{% block extrastyle %}
{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "djaken/css/view_note.css" %}" />
{% endblock %}

{% block title %}{{note.title}} | {{ site_title|default:_('Djaken') }}{% endblock %}

{% block content %}
    <div class="controls">
        <table class="outer">
            <tr>
                <td>
                    <table class="inner">
                        <tr>
                            <td class="control_button">
                                <a class="edit_button" title="{% trans 'Edit note' %}" href="{% url 'djaken:edit_note' note.pk %}"></a>
                            </td>
                            <td class="control_buttons">
                               {% if note.relevant %}
                                   <a title="{% trans 'Set as irrelevant' %}" href="{% url 'djaken:view_note_toggle_relevant' note.pk %}" class="toggle-control toggle-on"></a>
                               {% else %}
                                   <a title="{% trans 'Set as relevant' %}" href="{% url 'djaken:view_note_toggle_relevant' note.pk %}" class="toggle-control"></a>
                               {% endif %}
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </div>
    <div class="note_content">
        {{ note_content_html|safe }}
    </div>
    <div class="footer">
        {% if note.is_encrypted %}
            <p class="encryption_icon"></p>
        {% endif %}
        {% if note.relevant %}
            <p class="note_relevant">
                {% trans 'Relevant' %}
            </p>
        {% endif %}
        {% if not note.relevant %}
            <p class="note_not_relevant">
                {% trans 'Not Relevant' %}
            </p>
        {% endif %}
        <p>
            {% trans 'Modified on' %}
            <time datetime="{{note.modified|date:"c"}}">
                {{note.modified|date}}
            </time>
        </p>
        <p>
            {% trans 'Created on' %}
            <time datetime="{{note.created|date:"c"}}">
                {{note.created|date}}
            </time>
        </p>
    </div>
    <script type="text/javascript">
        window.onload = function() {
            history.replaceState("", "", "/view_note/{{note.id}}");
        }
        var links = document.links;
        for (var i = 0, linksLength = links.length; i < linksLength; i++) {
             if (links[i].hostname != window.location.hostname) {
                 links[i].target = '_blank';
             } 
        }
    </script>
{% endblock %}